#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

readonly TARGET_HOST=pi@octopi.local
readonly TARGET_PATH=/home/pi/thermostat-pi
readonly TARGET_ARCH=armv7-unknown-linux-gnueabihf
readonly SOURCE_PATH=./target/${TARGET_ARCH}/release/thermostat-pi

cross build --release --target=${TARGET_ARCH} --features vendored-openssl

rsync ./configuration.yaml ${TARGET_HOST}:/home/pi/configuration.yaml
rsync ${SOURCE_PATH} ${TARGET_HOST}:${TARGET_PATH}
ssh -t ${TARGET_HOST} ${TARGET_PATH}
