build: 
	cross build --release --target x86_64-unknown-linux-musl
	
test:
	curl -X POST https://xcww7vdjeumnnz65sr4dwpl3by0ofrwp.lambda-url.us-east-2.on.aws/ -H 'Content-Type: application/json' -d '{"record_date":"2022-11-17T15:50:00","thermostat_on":true,"temperature":"70.123","thermostat_value":"72"}'

deploy: build
	cp target/x86_64-unknown-linux-musl/release/push_temp bootstrap
	zip bootstrap.zip bootstrap
	aws lambda update-function-code --function-name PushTemp --zip-file fileb://./bootstrap.zip 
